// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdF2eNNYcYVCVsWUeF99mRJMLKjnvnIXs',
    appId: '1:1079223790444:android:947b4a123a8ae3a78b6149',
    messagingSenderId: '1079223790444',
    projectId: 'ddbox-427e4',
    databaseURL: 'https://ddbox-427e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ddbox-427e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfV19hvs2p7J7CHv6e6gPrzelaW9QqT00',
    appId: '1:1079223790444:ios:db998844c93bbeb58b6149',
    messagingSenderId: '1079223790444',
    projectId: 'ddbox-427e4',
    databaseURL: 'https://ddbox-427e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ddbox-427e4.appspot.com',
    androidClientId: '1079223790444-3vd4bl7n7hfbb2gnnsspk2bup1gpv6sl.apps.googleusercontent.com',
    iosClientId: '1079223790444-jbelovjl3etfav1g9tl21ma6stb8oit1.apps.googleusercontent.com',
    iosBundleId: 'com.ddbox.app.ddbox',
  );
}
