name: ddbox
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

# Dependencies specify other packages that your package needs in order to work. 3.1.4 <4.0.0
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_ui_database: ^1.3.11
  firebase_auth: ^4.15.3
  firebase_database: ^10.3.3
  flutter_lints: ^3.0.0
  firebase_core: ^2.13.0
  local_auth:
  intl_phone_number_input: ^0.7.3+1
  #firebase_auth: ^4.12.0
  libphonenumber: ^2.0.2
  google_sign_in: ^6.2.0
  sign_in_with_apple: ^5.0.0
  flutter_login: ^4.2.1
  #firebase_ui_database: ^1.3.11
  flutter_svg:
  cloud_firestore:
  webview_flutter: ^2.0.13
  video_player: ^2.8.2
  timezone: ^0.9.2
  flutter_local_notifications: ^16.1.0
  flutter_countdown_timer: ^4.1.0
  workmanager: ^0.5.2
  firebase_messaging: ^14.7.3
  app_settings: ^5.1.1
  fluttertoast: ^8.2.4
  get:
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator:
  permission_handler: ^11.1.0
  country_code_picker: ^3.0.0
  geocoding: ^2.1.1
  flutter_isolate: ^2.0.4
  intl: ^0.18.1
  lottie: ^3.0.0
  flutter_image_compress: ^2.1.0
  http: ^0.13.6
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  sendgrid_mailer: ^0.1.3
  mailer: ^6.1.0
  rxdart: ^0.27.7
  connectivity: ^3.0.6
  twilio_flutter: ^0.0.9
  another_flushbar: ^1.12.30
  chewie: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

  #android_alarm_manager: ^2.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-Bold.ttf

#  plugin:
#    platforms:
#      android:
#        package: com.ttlock.ttlock_flutter
#        pluginClass: TtlockFlutterPlugin
#      ios:
#        pluginClass: TtlockFlutterPlugin
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/locked.png
    - images/googlelogo.svg
    - images/applelogo.svg
    - images/forgotscreenimg.svg
    - images/splashlockimage.jpeg
    - images/logsicon.svg
    - images/dashboardotpicon.svg
    - images/abouticon.svg
    - images/vector.svg
    - images/help.svg
    - images/member.svg
    - images/logs.svg
    - images/settings.svg
    - images/touchtolock.png
    - images/touchtounlock.png
    - images/regenrateotp.svg
    - images/copy.svg
    - images/locksplash.svg
    - images/ttl.png
    - images/langicon.svg
    - images/sunicon.svg
    - images/termsicon.svg
    - images/logouticon.svg
    - images/un.png
    - images/lo.png
    - images/otpdashboard.svg
    - images/box.svg
    - images/boxidinotfoundicon.svg
    - images/location_icon.svg
    - images/lockstatusnotificationicon.svg
    - images/doorisknocked.svg
    - assets/circular_animation.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
